alertmanager:
  alertmanagerSpec:
    priorityClassName: ${alertmanager_priorityclass}
    logFormat: logfmt
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'general'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
      - match_re:
        namespace: 123|astrid-pxrae|astrid-uat-gbjbm|board-customers-meroa|capabilityplayground-3d931b6c-default|capabilityplayground-vwxyz|codeanalysis-yjlbr|controlcapacity-xgoja|customer-iam-ykpqn|customs-qjjyq|datadelivery-gexyo|ded-workshops-ljmra|demoplayground-lylbl|developer-platform-gkgeg|dfds-app-assets-vrbeb|dfds-logistics-route-mvjxl|direct-obozp|dojo-ens-yjvak|dotcom-seo-analytics-meerp|dotcom-website-infrast-kyyzm|dummy-vwxyz|enable-one-dfds-domain-znkro|ferry-cancellation-for-jpoxj|freight-book-ticket-olnma|freightbff-ypgjn|freightvoyage-eynbz|gtms-prod-reygq|haraldemojitest3-rjaok|hejhej-2f3a3304|logistics-documenthand-mjxpz|logistics-frontend-mlxyk|logistics-instruction-lezvq|logistics-instructions-boomq|logistics-integratedia-bqyxe|logistics-location-gozxp|logistics-map-mggjx|logistics-quote-stagin-zlpxz|logistics-quotes-eqxam|logistics-route-jgmoz|logistics-routes-bapbj|logistics-tracking-kyvem|managecustomers-kqmbo|manageequipmentlifecyc-xqxmx|managefleet-mjlyp|manageroutes-pqglk|migrate-public-sites-jqope|mlops-mmlml|notification-yjavj|offerproducts-qymnb|onboardcustomers-npxkm|onboardwifi-jqvrj|operateports-zekzl|operateships-mvrnv|package-holidays-nzxrj|passengerbffs-jqzab|passengerbooking-gbmvk|passengerpricing-zmjme|passengerrevmgmt-ybyyy|pax-booking-frontend-kkmgp|paxeventintegration-lgyny|rebate-vjnnx|run-source-netscaler-ypxem|sandbox-delete-me-rnyvq|sandbox-emcla-pmyxn|sandbox-hemor-lbprn|sandbox-operations-glxgq|sandbox-pwes-eaaqb|sandbox-raras-gmrox|sandbox-wicar-ypvvv|seabeast-gqxze|seabook-monitoring-jarry|segment-ui-beorp|service-transition-nalkj|smardataseldontest-qxgpy|smartdata-ats-xaqxj|smartdata-fuel-eff-xabvg|smartdata-fuel-optimiz-obbvp|smartdata-logfod-kqogy|smartdata-pbb-glmee|summarydeclaration-gjbpl|takepayment-qpkpk|terminal-search-aqnay|terminal-search-nonpro-gnjxj|terminal-unit-identifi-boako|test-area-a0b3ff2|test-end-to-end0-1ca9fd66|test-end-to-end1-a1fc255f|test-end-to-end3-c56a4853|test-end-to-end4-eykzn|testareaded-e9369b7|testareaded2-678df76|testcapabilityrole-egzoy|testendtoend5-c73e9e9e|testingadsync-yzmrx|testingadsync2-opgbn|testnodoublenscreati-bcf07274|testpelle-826a0440|uiam-usermanagement-nmmml|velocity-monitoring-qbokv|velocity-playground-onzxm|veocity-feedback-rexok|virtualworkstationdata-pvyme|p-project
        receiver: 'null'
      - match:
          alertname: AggregatedAPIDown
          name: 'v1beta1.metrics.k8s.io'
          namespace: 'default'
        receiver: 'null'
    receivers:
    - name: 'general'
      slack_configs:
      - channel: ${alertmanager_slack_channel}
        send_resolved: true
        api_url: ${alertmanager_slack_webhook}
        title: '{{ if eq .CommonLabels.severity "critical" }}<!channel>{{ else }}<!here>{{ end }} {{ .Alerts | len }} alerts - {{ .GroupLabels.alertname }}'
        text: "{{ range .Alerts }}\n*{{ .Annotations.description }}*\n*{{ .Annotations.message }}*\n*{{ .Labels.severity }}*\n{{ .Annotations.runbook_url }}\n{{ end }}"
    - name: 'null'