kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false

prometheus-node-exporter:
  priorityClassName: ${prometheus_node_exporter_priorityclass}

kube-state-metrics:
  priorityClassName: ${kube_state_metrics_priorityclass}