grafana:
  adminPassword: ${grafana_admin_password}
  priorityClassName: ${grafana_priorityclass}
  ingress:
    enabled: true
    path: ${grafana_ingress_path}
    hosts:
      - ${grafana_host}
    annotations:
      traefik.frontend.rule.type: PathPrefixStrip
  grafana.ini:
    auth.anonymous:
      enabled: true
    metrics:
      enabled: true
    server:
      domain: ${grafana_host}
      root_url: ${grafana_root_url}
  plugins:
  - grafana-polystat-panel

  notifiers:
    notifiers.yaml:
      notifiers:
        - name: ${grafana_notifier_name}
          type: slack
          uid: notifier1
          org_id: 1
          is_default: true
          send_reminder: true
          frequency: 24h
          disable_resolve_message: false
          # See  section for settings supporter for each
          # alert notification type.
          settings:
            recipient: ${grafana_slack_notifier_channel}
            uploadImage: true
            url: ${grafana_slack_webhook}
            username: alertbot
