---
modules:
  http_2xx:
    http:
      follow_redirects: true
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
    prober: http
    timeout: 5s
  http_401:
    http:
      follow_redirects: true
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      valid_status_codes:
        - 401
    prober: http
    timeout: 5s
  azure_appreg_auth:
    prober: http
    timeout: 5s
    http:
      follow_redirects: true
      tls_config:
        insecure_skip_verify: true
      valid_status_codes:
        - 402
      preferred_ip_protocol: ip4
      valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
      oauth2:
        client_id: ${client_id}
        client_secret: ${client_secret}
        token_url: ${token_url}
        scopes:
          - https://graph.microsoft.com/.default
